### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by alexanderkiehl** [shobrook/adrenaline#53]
Impossible to launch the code without any error, error in the DOM... 
On you website is the same, impossible to retrieve any repo. Seems it's not accurate.

**Comment by caaaaaleb** [comment]
+1

**Comment by goodroot** [comment]
Whatever proxy they're using to re-route requests is most likely getting hammered. Therefore, nothing is working.

**Comment by justinhartman** [comment]
Without much documentation I got it running by manually setting up an Auth0 application, set env variables and now can't go much further because the websocket isn't working. Looking at the production website they are running the WS off of wss://websocket-lb.useadrenaline.com so it seems to me the websocket is another app (potentially) that needs to run. There is no routes to configure what happens for example when the app tries to execute wss://websocket-lb.useadrenaline.com/answer_query so I can't see that what is made public here in this repo is the entire application. Pity, could have saved an hour had I known this isn't complete.

**Comment by jkbhagatio** [comment]
yep, I'm also locally getting a node js app client-side DOM exception: `URL 'undefinedanswer_query' is invalid.`

**Comment by lmsutools** [comment]
> Without much documentation I got it running by manually setting up an Auth0 application, set env variables and now can't go much further because the websocket isn't working. Looking at the production website they are running the WS off of wss://websocket-lb.useadrenaline.com so it seems to me the websocket is another app (potentially) that needs to run. There is no routes to configure what happens for example when the app tries to execute wss://websocket-lb.useadrenaline.com/answer_query so I can't see that what is made public here in this repo is the entire application. Pity, could have saved an hour had I known this isn't complete.

Hello, can you please tell me how to set env variables to paste the sk- api key and what else should I do? what is the Auth0 application? Thanks!

**Comment by rmdashrfv** [comment]
Serious question: Given the nature of the platform, wouldn't it make sense to plug the Adrenaline into Adrenaline and it would fix itself in a few seconds?

**Comment by lmsutools** [comment]
> Serious question: Given the nature of the platform, wouldn't it make sense to plug the Adrenaline into Adrenaline and it would fix itself in a few seconds?

I think it needs more fixes made by humans before going onto that.

**Comment by aliensouls** [comment]
this is possibly built on top of AutoGPT?  it's pretty bad to tell the truth, I connected the web version to my github repo of a simple html/css/js website code and it is pretty useless, can't find things in code unless I point it to exact location where I want it to find things 😄 .  I believe someone will develop something useful on top of AutoGPT soon, we just need to keep looking for the real quality products that are developed out there, and not fall for the "quick buck" scammers who try to charge $ "while it's hot" for half-assed 'services'.
